[mypy]
python_version = 3.12
ignore_missing_imports = True
no_implicit_optional = True
warn_return_any = False
warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
check_untyped_defs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_calls = True
strict_equality = True
no_implicit_reexport = True
